name: test-pr
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v6
        with:
          node-version: 24
          cache: yarn
      - name: test
        run: yarn run test
