name: Validate Files
on:
  workflow_run:
    workflows: [workflow-1]
    types:
      - completed
jobs:
  validate-html:
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: Get code on VM
        uses: actions/checkout@v6
      - name: check html file
        run: test -f index.html

  validate-js:
    runs-on: ubuntu-latest
    steps:
      - name: Get code on VM
        uses: actions/checkout@v6
      - name: check js file
        run: test -f script.js
  validate-code:
    needs: [validate-html, validate-js]
    runs-on: ubuntu-latest
    steps:
      - name: Get code on VM
        uses: actions/checkout@v6
      - name: test js file
        run: node --check script.js
      - name: test html file
        run: npx htmlhint index.html
