name: Validate Files
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Get code on VM
        uses: actions/checkout@v4
      - name: check html file
        run: test -f index.html
      - name: check js file
        run: test -f script.js
