name: Validate Files
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Get code on VM
        uses: actions/checkout@v6
      - name: check html file
        run: test -f index.html
      - name: check js file
        run: test -f script.js
      - name: test js file
        run: node --check script.js
      - name: validate css file
        run: npx --yes stylelint style.css
